# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20180502_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.CharField(choices=[(b'installed_products', b'Installed Products Report'), (b'portal_efficiency_report', b'Portal Efficiency Report'), (b'carbonblack_audit', b'Carbonblack Host Audit Report'), (b'mssp performance', b'Escalated Alerts Detail Report'), (b'executive', b'Executive Report Combined'), (b'cylance_billing', b'Cylance Billing Report'), (b'ttr_ttd', b'TTR/TTD Report'), (b'eula_acceptance', b'EULA Acceptance Report'), (b'users_last_login', b"Users' Last Login Report"), (b'organization', b'Organization Report'), (b'escalation_to_client', b'Escalation To Client Details Report'), (b'tenable', b'Tenable Vulnerability Report')], max_length=64),
        ),
        migrations.AlterField(
            model_name='report',
            name='typ',
            field=models.CharField(choices=[(b'pdf', b'PDF Document'), (b'docx', b'Word Document'), (b'xlsx', b'Excel Document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report',
            field=models.CharField(choices=[(b'installed_products', b'Installed Products Report'), (b'portal_efficiency_report', b'Portal Efficiency Report'), (b'carbonblack_audit', b'Carbonblack Host Audit Report'), (b'mssp performance', b'Escalated Alerts Detail Report'), (b'executive', b'Executive Report Combined'), (b'cylance_billing', b'Cylance Billing Report'), (b'ttr_ttd', b'TTR/TTD Report'), (b'eula_acceptance', b'EULA Acceptance Report'), (b'users_last_login', b"Users' Last Login Report"), (b'organization', b'Organization Report'), (b'escalation_to_client', b'Escalation To Client Details Report'), (b'tenable', b'Tenable Vulnerability Report')], max_length=64),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='typ',
            field=models.CharField(choices=[(b'pdf', b'PDF Document'), (b'docx', b'Word Document'), (b'xlsx', b'Excel Document')], max_length=32),
        ),
    ]
