# Generated by Django 2.2.7 on 2019-11-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190930_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.CharField(choices=[('carbonblack_audit', 'Carbonblack Host Audit Report'), ('cylance_billing', 'Cylance Billing Report'), ('mssp performance', 'Escalated Alerts Detail Report'), ('escalation_to_client', 'Escalation To Client Details Report'), ('eula_acceptance', 'EULA Acceptance Report'), ('executive', 'Executive Report Combined'), ('installed_products', 'Installed Products Report'), ('organization', 'Organization Report'), ('portal_efficiency_report', 'Portal Efficiency Report'), ('tenable', 'Tenable Vulnerability Report'), ('ttr_ttd', 'TTR/TTD Report'), ('users_last_login', "Users' Last Login Report")], max_length=64),
        ),
        migrations.AlterField(
            model_name='report',
            name='typ',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('xlsx', 'Excel Document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='weekly', max_length=32),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='report',
            field=models.CharField(choices=[('carbonblack_audit', 'Carbonblack Host Audit Report'), ('cylance_billing', 'Cylance Billing Report'), ('mssp performance', 'Escalated Alerts Detail Report'), ('escalation_to_client', 'Escalation To Client Details Report'), ('eula_acceptance', 'EULA Acceptance Report'), ('executive', 'Executive Report Combined'), ('installed_products', 'Installed Products Report'), ('organization', 'Organization Report'), ('portal_efficiency_report', 'Portal Efficiency Report'), ('tenable', 'Tenable Vulnerability Report'), ('ttr_ttd', 'TTR/TTD Report'), ('users_last_login', "Users' Last Login Report")], max_length=64),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='typ',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('xlsx', 'Excel Document')], max_length=32),
        ),
    ]
